# Generated by Django 5.2.4 on 2025-07-31 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_ticket_complaint_name_alter_ticket_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='hod_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
