# Generated by Django 5.2.4 on 2025-07-31 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_ticket_hod_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved by HOD', 'Approved by HOD'), ('Disapproved by HOD', 'Disapproved by HOD')], default='Pending', max_length=50),
        ),
    ]
